- BE/api/comments.js
- BE/api/documentation/index.html
- BE/api/index.js
- BE/api/recipes.js
- BE/api/reviews.js
- BE/api/tags.js
- BE/api/users.js
- BE/index.js
- BE/package-lock.json
- BE/package.json
Added placeholder endpoints with messages telling details about the endpoints. Added folder for API documentation.
> 6 write placeholder endpoints

- FE/package-lock.json
- FE/package.json
- FE/src/App.jsx
- FE/src/components/Account.jsx
- FE/src/components/Admin.jsx
- FE/src/components/EditRecipe.jsx
- FE/src/components/Login.jsx
- FE/src/components/MainPage.jsx
- FE/src/components/NavBar.jsx
- FE/src/components/NewRecipe.jsx
- FE/src/components/Recipes.jsx
- FE/src/components/SingleRecipe.jsx
- FE/src/main.jsx
Front end routes, component files, and latest Vite and installed react-router-dom
> 61 frontend placeholder routes in app

- BE/db/index.js
- BE/db/seed.js
Pull request for 5 write and successfully run seed. Seed runs successfully and test functions work.
> 5 write and successfully run seed

- FE/src/App.jsx
- FE/src/components/NavBar.jsx
- package-lock.json
NavBar file renders Home and Recipes links, and conditionally renders link to Account & Admin for admin, Account for user, and Login/Register when neither is true.
> Added NavBar placeholder

- BE/db/index.js
- BE/db/seed.js
1. getUserPageRecipesByUser (includes parent data but no child data)
getUserPageReviewsByUser (includes parent data but no child data)
getUserPageCommentsByUser (includes parent data)
2. getUserInfoWithPasswordById (the other one does not include the password anymore. Also getAllUsers does not include the password anymore)
3. reviewCount functionality works when creating a review
> 67 get user data db functions

- BE/api/index.js
- BE/api/users.js
- BE/api/utils.js
- BE/index.js
Created register endpoint, added body parser, set up user Auth, added requireUser function
> 10 register endpoints

- BE/api/users.js
> 8-login-endpoints

- BE/db/index.js
- BE/db/seed.js
2nd attempt at this branch. Added db functions:
getRecipesByTagName(tagName)
getUserRecipesByTagName(userId, tagName)
getReviewedRecipesPage()
destroyCommentById(commentId)
destroyReviewById(reviewId)
destroyTagById(tagId)
destroyRecipeById(recipeId)
destroyUserById(userId)
All tested successfully.
These should be the rest of the db functions we need for MVP.  So every "db functions" task has been moved over to code review.
> 71 tags db functions 2

- BE/db/index.js
- BE/db/seed.js
I created a getUserPageById and trimmed all of the data down within the queries of the embedded functions. Overall the data being sent to the endpoint functions are much better formatted for front end use now, based on the wireframe we discussed.
I also trimmed the data down within the queries of the functions that make up getAllRecipesPage and getReviewedRecipesPage.
Finally I added getTagsByUser.
Ultimately I made a lot of extra work for myself, basing the original test functions too much off of Juicebox. Many of those test functions are useless now. I will continue to call them in the seed file though, and if we want to clean it all up later we can do that.
I think Larry and I together can easily get all of the endpoints fully working by Thursday. I imagine authentication is gonna be …
> 75 restructuring data for endpoints

- FE/src/components/SingleRecipe.jsx
Added simple placeholder for Single Recipe card. Will eventually use useParams to select recipeId but for this I just fed it one id since simulating a fetch call seemed unnecessary.
> Single Recipe placeholder

- FE/src/components/Admin.jsx
able to render a list of user information and naviagte to their page, userBio page still to come. Can view a list of recipes and their reviews and navigate to recipe, single recipe to come. Location for tier 2 tag modification added.
> Basic Admin viewing placeholder page

- BE/api/comments.js
- BE/api/recipes.js
- BE/api/reviews.js
- BE/api/tags.js
- BE/api/utils.js
- BE/db/index.js
> 17 recipes endpoints

- BE/api/users.js
> fixed major password bug

- FE/src/components/NewRecipe.jsx
Added form that allows for dynamic user input for ingredients, procedure and notes. Will need get call for tags, post on submit and user verification.
> Added Create Form sans api calls

- FE/src/components/Recipes.jsx
Added a search bar to the recipes component. Added a message if no recipes are found. Filters the main list, that way it is constantly filtering.
> 29 search react

- BE/api/users.js
- FE/src/App.jsx
- FE/src/components/Login.jsx
- FE/src/components/NavBar.jsx
Fixed logout functionality in navbar, added admin to res from login and register endpoints, admin state added to Main.jsx
> 12-log-out-react

- FE/index.html
- FE/src/App.jsx
- FE/src/components/NewRecipe.jsx
- FE/src/index.css
This is the bare bones styling based on the style doc. In order to look how I intended several things need to be done that will cause merge conflicts for ya'll so I didn't include them in these commits, so you should on the components you are working on.
1. All images in the entire project need to have their sizing attributes removed from the actual element. Image sizing is now handled by the CSS.
2. The userUpdateForm  on the account page REALLY needs to be inside of the userInfo div.
3. SingleRecipe instructions need to be in their own div for me to proceed any further. Also comments and Reviews need their own divs on the page.
4. The form inside of the NewRecipe component needs to have a className of newRecipeForm.
5. Consider moving the input elements outside of the labels and linking …
> 27 basic styling

- BE/db/seed.js
hash default user passwords so that you can log in with them.
> fixed default user passwords

- FE/src/App.jsx
- FE/src/components/Account.jsx
- FE/src/components/CommentCard.jsx
- FE/src/components/Login.jsx
- FE/src/components/NavButton.jsx
- FE/src/components/RecipeCard.jsx
- FE/src/components/ReviewCard.jsx
- FE/src/components/TagInfo.jsx
- FE/src/components/UserComments.jsx
- FE/src/components/UserInfo.jsx
- FE/src/components/UserProfile.jsx
- FE/src/components/UserRecipes.jsx
- FE/src/components/UserReviews.jsx
Please check over how token is being handled in the UserInfo and I am unsure how to properly navigate between the nested route so I left that alone for now, will correct on a new branch. Account also need to have a component that handles the tab section based on the tags in userRecipes- can reuse on Main?
> 84 fe refine and break apart account into components

- BE/api/uploadImage.js
- BE/db/seed.js
- BE/package-lock.json
- BE/package.json
Added images to seed data, added several new recipes, installed cloudinary, added functionality to upload images.
> 116-recipe-seed-images

- FE/src/App.jsx
- FE/src/components/Admin.jsx
- FE/src/components/UploadImage.jsx
This component will be used later to replace front end posting of imageUrls. Combined with some changes on the backend, this will allow us to upload a photo to cloudinary and use that imgUrl in the database instead of having to directly post an imgUrl. Will not be incorporated until after MVP.
> Add upload image component

- BE/api/users.js
- FE/src/App.jsx
- FE/src/components/Login.jsx
- FE/src/components/NavBar.jsx
- FE/src/components/SingleRecipe.jsx
Login and register endpoints respond with username
currentUser state is set to username from response
currentUser and admin are reset on logout
user links added to single recipe page
> 125 single recipe add user links

- BE/README.md
- BE/api/documentation/index.html
- BE/api/documentation/styles.css
- BE/api/reviews.js
finished api documentation. fixed a bug that was causing server to crash.
> 112 api documentation

- BE/db/index.js
- FE/src/App.jsx
- FE/src/components/Admin.jsx
- FE/src/components/NavBar.jsx
- FE/src/components/SingleRecipe.jsx
fixed admin stuff
user links for admin stuff
> 131 add all user links

- FE/src/App.jsx
- FE/src/components/RecipeCard.jsx
- FE/src/components/Recipes.jsx
Recipes.jsx makes real get call. Chnaged rendering of the search bar so that it would work together with the all recipes list. Changed edit button on recipe card to render for admin only.
> All Recipes get

- FE/src/components/Account.jsx
- FE/src/components/CommentCard.jsx
- FE/src/components/RecipeCard.jsx
- FE/src/components/ReviewCard.jsx
- FE/src/components/UserComments.jsx
- FE/src/components/UserRecipes.jsx
- FE/src/components/UserReviews.jsx
Added a cancel button for form, if password is "" and updatedUser is null form will cancel, password will not push to API if "". password and confirmPassword states are reset to "" after user form has submitted. Comments just had a data pathing issue.
> Account PATCH bug and comments display fixed

- BE/db/index.js
this fixes the user/:userId fetch
> Fixing get public user page

- FE/src/App.jsx
- FE/src/components/CommentCard.jsx
- FE/src/components/MainPage.jsx
- FE/src/components/RecipeCard.jsx
- FE/src/components/ReviewCard.jsx
- FE/src/components/UserComments.jsx
- FE/src/components/UserProfile.jsx
- FE/src/components/UserReviews.jsx
user links. everywhere. EVERYWHERE.
> 141 all user links p2

- FE/src/components/Pagination.jsx
Added component for pagination. Have not yet hooked it up because I'm waiting on merges from other branches. Uses the RecipeCard Component and separates them into pages of any length you set.
> 151 pagination component

- FE/src/components/Loading.jsx
- FE/src/index.css
Loading component file and styles added. Will have to be hooked up to conditionally render component by component. State variable set to true, that is set to false when loading is complete.
> 153 added loading component

- FE/src/components/EditRecipe.jsx
- FE/src/components/Recipes.jsx
Added Edit recipe form. Form is functional with a few caveats: The title field cannot be changed, and when adding a Note it does not appear on the card, but it does show up in the result object so I think it is a front end issue. Also changed Recipes.jsx api url.
> Edit Recipe form

- FE/src/App.jsx
- FE/src/components/Admin.jsx
- FE/src/components/FormTags.jsx
- FE/src/components/NewRecipe.jsx
Created route protection, edited create recipe page to include select elements rather than datalist.
> 147 route protection for create recipe

- FE/src/components/Recipes.jsx
- FE/src/components/RecipesPageTabs.jsx
- FE/src/index.css
Added a tag filter to the main page. The searchbar still works for tags. I opted for checkboxes rather than buttons. If we don't like this I can change it to buttons.
> 149 main page tags

- FE/src/components/Recipes.jsx
tag filter is fixed. I had to add one more state
> Fix Tag Filter

- FE/src/components/Account.jsx
- FE/src/components/Admin.jsx
- FE/src/components/EditRecipe.jsx
- FE/src/components/Login.jsx
- FE/src/components/MainPage.jsx
- FE/src/components/Recipes.jsx
- FE/src/components/RecipesByTag.jsx
- FE/src/components/SingleRecipe.jsx
- FE/src/components/UserProfile.jsx
- FE/src/components/UserRecipes.jsx
I set up loading and pagination on all necessary pages. Will probably need to be rebased after Jared's thing. Please let me know if I missed any spots where the pagination or loading would be useful.
> added loading and pagination

- BE/api/recipes.js
- BE/api/uploadImage.js
- BE/api/users.js
- BE/db/index.js
- BE/index.js
- FE/src/App.jsx
- FE/src/components/Account.jsx
- FE/src/components/EditRecipe.jsx
- FE/src/components/NewRecipe.jsx
- FE/src/components/UploadImage.jsx
- FE/src/components/UserProfile.jsx
this should allow for user uploaded images rather than urls. I have not tested changes yet, but will update once I have. You will also have to supply the cloudinary api info in your dotenv file for the BE to work on your local machine. I will post the creds in slack.
> 137-image-upload

- FE/src/components/CommentCard.jsx
- FE/src/components/Pagination.jsx
- FE/src/components/RecipeCard.jsx
- FE/src/components/ReviewCard.jsx
- FE/src/components/UserComments.jsx
- FE/src/components/UserRecipes.jsx
- FE/src/components/UserReviews.jsx
All the recipe titles will now link to their specific recipe across recipe, review, and comment cards. If an array of Recipes, Reviews, Comments is empty it will tell the user there is currently no content for that section and prevent the mapping of the array.
> Recipe Title Navigation on Cards & "No Content"

- FE/src/components/RecipesByTag.jsx
- FE/src/components/TagInfo.jsx
made tags into links, styling taken care of elsewhere.
> card-links

- FE/src/components/Account.jsx
- FE/src/components/Admin.jsx
- FE/src/components/EditRecipe.jsx
- FE/src/components/FormTags.jsx
- FE/src/components/Login.jsx
- FE/src/components/MainPage.jsx
- FE/src/components/NewRecipe.jsx
- FE/src/components/Recipes.jsx
- FE/src/components/RecipesByTag.jsx
- FE/src/components/SingleRecipe.jsx
- FE/src/components/UserProfile.jsx
- FE/src/index.css
added api url and edited styles
> add-api-url

- BE/api/recipes.js
- BE/api/users.js
- FE/src/components/general/UploadImage.jsx
- FE/src/components/general/handleUpload.js
- FE/src/components/product/EditRecipe.jsx
- FE/src/components/product/NewRecipe.jsx
- FE/src/components/users/Account.jsx
- FE/src/components/users/UserProfile.jsx
fixed image upload and userInfo styling
> Image upload fix

- FE/src/index.css
fixed login and recipe form responsiveness
> mobile-responsive-updates

- FE/src/components/users/Admin.jsx
added admin status on all users
> Admin Status On All Users

- FE/src/components/product/SingleRecipe.jsx
- FE/src/components/users/Admin.jsx
Added Larry's TagInfo component to the tag list in Admin and SingleRecipe
> Rest of tag info links

- FE/src/components/users/Login.jsx
made fail messages for login and register separate states, also changed the loading condition so that everything looks a little cleaner (register box no longer vanishes)
> Login Page: Fail Message States + Loading

- FE/src/components/product/Recipes.jsx
- FE/src/components/product/RecipesPageTabs.jsx
- FE/src/index.css
added clear tags button working and styled
> Clear Selected Tags

- FE/src/components/users/Account.jsx
fixed admin cannot edit account bug
> admin-data-fix

- FE/src/components/users/Account.jsx
- FE/src/index.css
fixed minor formatting bug for long loading times.
> Loading format fix

- FE/src/App.jsx
- FE/src/components/general/RecipesByTag.jsx
- FE/src/components/product/MainPage.jsx
The admin prop for recipe card was not passed down through every parent component. I fixed that. We used to have this, but it got deleted somehow
> Add Back Recipe Card Edit

- BE/api/recipes.js
added a check on create and edit recipe that prevents blank tags from being added
> BE: Tags Cannot Be Blank

- BE/api/users.js
admin can delete users through postman. They cannot delete themselves
> BE: Delete User Endpoint (requireAdmin)

- BE/api/recipes.js
- BE/db/index.js
- FE/src/components/product/EditRecipe.jsx
- FE/src/components/product/FormTags.jsx
- FE/src/components/product/NewRecipe.jsx
- FE/src/components/users/Admin.jsx
This pull request is for after the presentation. PLEASE test by **replacing** API URLs with localhost:3000.
Features:
FormTags now has zero tags as an option. 
Create Recipe form defaults to zero tags.
Each mapped tag within FormTags now has a write-in option.
Users cannot submit the creation/edit unless tags only contain letters of the alphabet and are not completely blank.
NewRecipe component does not submit tag array to req.body if tagList.length == 0.
Admin can delete tags one at a time through the admin recipe tags section.
UpdateRecipe now allows for an empty tag array to be submitted, which removes all recipe_tag junction rows with that recipe's id.
Recipe POST and PATCH endpoints check to make sure only letters of the alphabet are being used in tag names. This includes making sure …
> Tag Write In / No Tags / Tag Content Protections / Delete Tag (FE)

- FE/src/components/general/StarButtons.jsx
- FE/src/components/product/SingleRecipe.jsx
- FE/src/index.css
ratings with stars instead of dropdown.
> star-buttons
